### ISSUE TITLE
Roadmap for V1

### ISSUE THREAD

**Issue by holasoyeddy** [holasoyeddy/gofu#1]
This is a list of features that we want to finish prior to releasing an official v1 version:

- [ ] Cross-platform support for Linux, Darwin and Windows
- [ ] A repository to upload Gofu templates
- [ ] Proper documentation
- [ ] Distribution via Homebrew for Darwin
- [ ] Distribution via apt-get for Debian
- [ ] Distribution via yum for Fedora
- [ ] EXE installer for Windows.

This list may change in the future.
